apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgImdoY3IuaW8iOiB7ImF1dGgiOiAiZEc5MllYSnBjMk5vWkhWeVlXeGxlVHBuYVhSb2RXSmZjR0YwWHpFeFFVNDBORGRPVVRBeFNGaGFSR1J1V0dObFJXZGZNa2xMVEdKWWRWRktRVkUxYldWVFdYRklOM2wwTlZVNFpreFBZelZSVVhJMVJGUTJhRXRHYVd0M1NWcEROa1pNUVRSSGN6RnJSMmhuWVZNPSJ9CiAgICAgICAgfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9LAoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9Cg==

type: kubernetes.io/dockerconfigjson
